version: '3'
services:
  web:
    image: dockimple:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      DATABASE_NAME: people
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: mysql
    depends_on:
      - mysql
    command: bash -c "sh wait-for mysql:3306 -- npm start"
  mysql:
    image: db:latest
    restart: always
    ports:
      - 3308:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080